[package]
name = "narictl"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true

[dependencies.narictl_lib]
path = "../narictl_lib"
